### ISSUE TITLE
Hooks and code splitting?

### ISSUE THREAD

**Issue by wmertens** [thearnica/react-uid#15]
It's not clear from the readme how to use hooks and code splitting?

**Comment by theKashey** [comment]
Hey mate :)

- hooks - just use it
  - `useUID` will give you just a UID, 1-2-3-4-5
  - `useUIDSeed` will give you a fabric function to generate more 'ids' for you

- code splitting. In terms of persistent UIDs especially with Server Side Rendering - just place `<UIDFork>` before splitting point to create a new "branch" of UIDs. 1-2-3-*FORK*4.1-4.2-4.3-

**Comment by wmertens** [comment]
Hi Anton :)

So that would make my makeSplitPoint function into:

```js
export const makeSplitPoint = (fn, options) => {
	const ssr = !options || options.ssr == null || options.ssr
	const noAutoImport = options && options.noAutoImport != null
		? options.noAutoImport
		: !ssr
	const Cmp = importedComponent(fn, {
		LoadingComponent: DefaultLoading,
		...options,
		noAutoImport,
	})
	if (ssr) return props => <UIDFork><Cmp {...props} /></UIDFork>
	class NoSsr extends React.Component {
		state = {mounted: false}

		componentDidMount() {
			this.setState({mounted: true})
		}

		render() {
			return this.state.mounted ? <UIDFork><Cmp {...this.props} /></UIDFork> : false
		}
	}
	return NoSsr
}
```

Right?

**Comment by theKashey** [comment]
Yep, all correct. That would help you maintain consistent UIDs between SSR and CSR.
