### ISSUE TITLE
Produce CSS valid ids

### ISSUE THREAD

**Issue by pgjones** [thearnica/react-uid#30]
Numeric IDs are great with HTML5 but not so with CSS which requires 

> Attribute values must be a valid CSS identifiers or String.

As I understand this modules code the UIDs are numeric, so I prefix them with a character 
```
const uid = `s${useUID()}`;
```
To avoid errors like, `'#2' is not a valid selector`. Given the likely usage of this I think it would be nice if it produces CSS valid ids by default.

**Comment by theKashey** [comment]
Just changing default prefix...

**Comment by pgjones** [comment]
Thanks, and thanks for the library.

**Comment by theKashey** [comment]
The new version has not yet been released.

**Comment by theKashey** [comment]
Decided to not prefix IDs automatically - that would cause a major version change, but let you specify what's needed via `UIDReset` - #34

**Comment by leepowelldev** [comment]
I don't believe this change creates css valid id's - the prefix needs to come before the numeric value. [https://css-tricks.com/ids-cannot-start-with-a-number/](https://css-tricks.com/ids-cannot-start-with-a-number/) - this change creates `number + prefix` rather than `prefix + number`

**Comment by theKashey** [comment]
Because you are looking to `UIDFork`, not `UIDReset` which is just 
```js
export const UIDReset: React.SFC<WithPrefix> = ({children, prefix = ''}) => (
  <source.Provider value={createSource(prefix)}>{children}</source.Provider>
);
```

**Comment by leepowelldev** [comment]
Ah sorry, my bad - not enough coffee!

**Comment by theKashey** [comment]
Here, take some: ☕️☕️☕️☕️☕️☕️

**Comment by leepowelldev** [comment]
Haha, thanks.

Can I just check something, as we're looking at using thie library to replace `shortid` throughout our codebase to make it SSR friendly. In the docs is says that `UIDFork` is SSR safe, however this components seems to consume `UIDConsumer` and that consumes `UID` which is documentated as "might not be SSR friendly". Should we stay away from using `UIDFork`?

**Comment by theKashey** [comment]
`UID` is just not "context aware" Component, what's why it is not "SSR-safe", however `UIDForm` is giving it an `idSource` prop, removing it default to a global counter, so it's absolutely safe to use it.
It's more about - `Fork` is using `UID` in a form you will never be happy to use it. That's why `UID` is deprecated,... and still in use internally.
