### ISSUE TITLE
Array of uids 

### ISSUE THREAD

**Issue by iammugik** [thearnica/react-uid#36]
I want to make an accessible tabs component. In my case there are two loops for render tabs and panels. Please clarify how to assign ids of loop's item to each on other respectively using useUIDSeed (or another approach)? First thing that comes to mind is make two arrays of uids, but I'm not sure that is the right way.
```js
tabs.map(tab =>
<Tab
    key={seed(tab)}
    id={seed(tab)}
    aria-controls={panel ID by index ??}
    role="tab"
>
...
panels.map(panel =>
<Panel
    key={seed(panel)}
    id={seed(panel)}
    role="tabpanel"
    aria-labelledby={tab ID by index ??}
/>
```

**Comment by theKashey** [comment]
So you have to do literally what you want - connect tab and pannel by index, however give a unique index to the browser
```js
tabs.map((tab, index) =>
<Tab
key={seed(tab)}
id={seed(tab)}
aria-controls={seed(panels[index])}
role="tab"

...
panels.map((panel, index) =>
<Panel
key={seed(panel)}
id={seed(panel)}
role="tabpanel"
aria-labelledby={seed(tabs[index]}
/>
```

**Comment by iammugik** [comment]
Exactly! That works, thank you!)
