### ISSUE TITLE
SSR issues with React Strict Mode

### ISSUE THREAD

**Issue by ramosbugs** [thearnica/react-uid#60]
Firstly, thanks for this great little library!

I've been experimenting with enabling React [Strict Mode](https://reactjs.org/docs/strict-mode.html) on my project to discover potential bugs. One of the things Strict Mode does is to invoke lifecycle methods multiple times to find unexpected side effects. It looks like this only happens on the client side, and it has the unfortunate effect of incrementing each ID twice.

If we look at the example at https://codesandbox.io/s/kkmwr6vv47, it returns the following IDs:
```
top level (One) key:1-1
+ nested element 1: 1-2
+ nested element 2: 1-3-1
top level (Two) key:2-1
+ nested element 1: 2-2
+ nested element 2: 2-3-1
top level (Three) key:3-1
+ nested element 1: 3-2
+ nested element 2: 3-3-1
```

If we wrap that example in `<React.StrictMode>` (see https://codesandbox.io/s/react-uid-example-forked-ie935), we get:
```
top level (One) key:2-2
+ nested element 1: 2-4
+ nested element 2: 2-6-2
top level (Two) key:4-2
+ nested element 1: 4-4
+ nested element 2: 4-6-2
top level (Three) key:6-2
+ nested element 1: 6-4
+ nested element 2: 6-6-2
```

I'm not sure what the right fix is, but ideally strict mode shouldn't cause any observable changes to the output, since these may cause breakages in future versions of React (e.g., once they enable concurrent rendering by default).

**Comment by theKashey** [comment]
Hey, unfortunately, this is a known limitation of a StrictMode which intentionally breaks logic like `useUID`.

The only possible fix is to update to __React 18__ and use the _React-backed_ `useId` hook - https://github.com/reactwg/react-18/discussions/111

**Comment by thearnica** [comment]
As per current package description
> Not compatible with Strict or Concurent mode. Consider using native useId(React 18) hook instead.
