### ISSUE TITLE
Build is not working correctly

### ISSUE THREAD

**Issue by maulik1729** [thearnica/react-uid#82]
`
export const UIDReset: React.FC<React.PropsWithChildren<WithPrefix>> = ({ children, prefix = '' }) => {
  const [valueSource] = useState(() => createSource(prefix));
  return <source.Provider value={valueSource}>{children}</source.Provider>;
};
`

This code is getting transpiling to 

`
export var UIDReset = function (_a) {
    var children = _a.children, _b = _a.prefix, prefix = _b === void 0 ? '' : _b;
    var z = createSource(prefix);
    return (React.createElement(source.Provider, { value: z  }, children));
};
`

Which is wrong because in this createSource is getting called on every rerender which leads to new reference of valueSource. Which causes rerendering of every component where we use this context.

Need to fix build process for this.

**Comment by theKashey** [comment]
This is very very weird

**Comment by maulik1729** [comment]
@theKashey for now we can change useState to useMemo or fix build issue of https://github.com/TheUiTeam/lib-builder. What would you recommend?

**Comment by theKashey** [comment]
Rebuild is mitigating the problem. Really not sure about the root cause 🤷‍♂️

**Comment by thearnica** [comment]
Fixed in 2.3.3

**Comment by maulik1729** [comment]
@thearnica Thanks for fixing this.  Can you please explain fix?

**Comment by theKashey** [comment]
Fix === Rebuild. We were not able to reproduce the root cause, even if it was persistent for the last couple of versions.

The root cause is unknown.
